/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface ServiceAccountsGetQuery {
    /**
     * The ID of the requested service account.
     */
    id: string;
}
