/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {}
 */
export interface ArticlesCountQuery {
    /**
     * The ancestor directory of the articles.
     */
    ancestor?: string;
    /**
     * Filters for articles belonging to any of the provided parts.
     */
    appliesToParts?: string | string[];
    /**
     * Filter for the type of articles. If this is not provided, then
     * articles that are not content blocks are returned.
     */
    articleType?: DevRev.ArticleType | DevRev.ArticleType[];
    /**
     * Filters for articles authored by any of the provided users.
     */
    authoredBy?: string | string[];
    /**
     * Filters for articles created by any of the provided users.
     */
    createdBy?: string | string[];
    /**
     * Filters for articles modified by any of the provided users.
     */
    modifiedBy?: string | string[];
    /**
     * Filters for articles owned by any of the provided users.
     */
    ownedBy?: string | string[];
    /**
     * Filter for the scope of the articles. If this is not provided, then
     * only external articles are returned.
     */
    scope?: number | number[];
}
