/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "string"
 *     }
 */
export interface PartsGetQuery {
    /**
     * The ID of the part to retrieve.
     */
    id: string;
}
