/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {}
 */
export interface PartsListQuery {
    /**
     * Filters for parts created by any of these users.
     */
    createdBy?: string | string[];
    /**
     * The cursor to resume iteration from. If not provided, then iteration
     * starts from the beginning.
     */
    cursor?: string;
    /**
     * The maximum number of parts to return. The default is '50'.
     */
    limit?: number;
    /**
     * The iteration mode to use, otherwise if not set, then "after" is
     * used.
     */
    mode?: DevRev.ListMode;
    /**
     * Filters for parts of the provided name(s).
     */
    name?: string | string[];
    /**
     * Filters for parts owned by any of these users.
     */
    ownedBy?: string | string[];
    /**
     * Number of levels to fetch the part hierarchy up to.
     */
    parentPartLevel?: number;
    /**
     * Part IDs to fetch the hierarchy for. Required if any parent_part.\*
     * fields are provided.
     */
    parentPartParts?: string | string[];
    /**
     * Filters for parts of the provided type(s).
     */
    type?: DevRev.PartType | DevRev.PartType[];
}
