/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {}
 */
export interface UomsCountQuery {
    /**
     * List of aggregation types for filtering list of UOMs.
     */
    aggregationTypes?: DevRev.AggregationDetailAggregationType | DevRev.AggregationDetailAggregationType[];
    /**
     * List of Unit of Measurement (UOM) DONs to be used in filtering
     * complete list of UOMs defined in a Dev Org.
     */
    ids?: string | string[];
    /**
     * List of metric names for filtering list of UOMs.
     */
    metricNames?: string | string[];
    /**
     * List of part IDs for filtering list of UOMs.
     */
    partIds?: string | string[];
    /**
     * List of product IDs for filtering list of UOMs.
     */
    productIds?: string | string[];
    /**
     * List of unit types for filtering list of UOMs.
     */
    unitTypes?: DevRev.UnitType | DevRev.UnitType[];
}
