/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {}
 */
export interface OrgSchedulesListQuery {
    /**
     * Creator ID the filter matches.
     */
    createdById?: string | string[];
    /**
     * The cursor to resume iteration from. If not provided, then iteration
     * starts from the beginning.
     */
    cursor?: string;
    /**
     * Max number of organization schedules returned in a page. Default is 50.
     */
    limit?: number;
    /**
     * The iteration mode to use, otherwise if not set, then "after" is
     * used.
     */
    mode?: DevRev.ListMode;
    /**
     * The organization schedule statuses the filter matches.
     */
    status?: DevRev.OrgScheduleStatus | DevRev.OrgScheduleStatus[];
}
