/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         account: "ACC-12345",
 *         id: "REV-AbCdEfGh"
 *     }
 */
export interface RevOrgsGetQuery {
    /**
     * The ID of account for which default Rev organization is to be
     * fetched.
     */
    account?: string;
    /**
     * The ID of the required Rev organization.
     */
    id?: string;
}
