/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "ACC-12345"
 *     }
 */
export interface AccountsGetQuery {
    /**
     * The ID of the account to be retrieved.
     */
    id: string;
}
