/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {}
 */
export interface WorksListQuery {
    /**
     * Filters for work belonging to any of the provided parts.
     */
    appliesToPart?: string | string[];
    /**
     * Filters for work created by any of these users.
     */
    createdBy?: string | string[];
    /**
     * The cursor to resume iteration from. If not provided, then iteration
     * starts from the beginning.
     */
    cursor?: string;
    /**
     * Filters for custom fields.
     */
    customFields?: Record<string, unknown>;
    /**
     * Filters for issues with any of the provided Accounts.
     */
    issueAccounts?: string | string[];
    /**
     * Filters for issues with any of the provided priorities.
     */
    issuePriority?: DevRev.IssuePriority | DevRev.IssuePriority[];
    /**
     * Filters for issues with any of the provided priority enum ids.
     */
    issuePriorityV2?: number | number[];
    /**
     * Filters for issues with any of the provided Rev organizations.
     */
    issueRevOrgs?: string | string[];
    /**
     * Filters for records with any of the provided SLA stages.
     */
    issueSlaSummaryStage?: DevRev.SlaSummaryStage | DevRev.SlaSummaryStage[];
    /**
     * Filters for issues with any of the sprint.
     */
    issueSprint?: string | string[];
    /**
     * Filters for issues with any of the provided subtypes.
     */
    issueSubtype?: string | string[];
    /**
     * The maximum number of works to return. The default is '50'.
     */
    limit?: number;
    /**
     * The iteration mode to use, otherwise if not set, then "after" is
     * used.
     */
    mode?: DevRev.ListMode;
    /**
     * Filters for opportunities belonging to any of the provided accounts.
     */
    opportunityAccount?: string | string[];
    /**
     * Filters for opportunities with any of the provided contacts.
     */
    opportunityContacts?: string | string[];
    /**
     * Filters for opportunity with any of the provided subtypes.
     */
    opportunitySubtype?: string | string[];
    /**
     * Filters for work owned by any of these users.
     */
    ownedBy?: string | string[];
    /**
     * Filters for work reported by any of these users.
     */
    reportedBy?: string | string[];
    /**
     * Fields to sort the works by and the direction to sort them.
     */
    sortBy?: string | string[];
    /**
     * Filters for records in the provided stage(s) by name.
     */
    stageName?: string | string[];
    /**
     * Filters for issues that are staged.
     */
    stagedInfoIsStaged?: boolean;
    /**
     * Filters for works with selected sync statuses.
     */
    syncMetadataLastSyncInStatus?:
        | DevRev.SyncMetadataFilterSyncInFilterStatus
        | DevRev.SyncMetadataFilterSyncInFilterStatus[];
    /**
     * Filters for works modified with selected sync units.
     */
    syncMetadataLastSyncInSyncUnit?: string | string[];
    /**
     * Filters for works with selected sync statuses.
     */
    syncMetadataLastSyncOutStatus?:
        | DevRev.SyncMetadataFilterSyncOutFilterStatus
        | DevRev.SyncMetadataFilterSyncOutFilterStatus[];
    /**
     * Filters for works modified with selected sync units.
     */
    syncMetadataLastSyncOutSyncUnit?: string | string[];
    /**
     * Filters for issues synced from this specific origin system.
     */
    syncMetadataOriginSystem?: string | string[];
    /**
     * Filters for work with any of the provided tags.
     */
    tags?: string | string[];
    /**
     * Filters for tickets with any of the provided channels.
     */
    ticketChannels?: DevRev.TicketChannels | DevRev.TicketChannels[];
    /**
     * Filters for tickets belonging to specific groups.
     */
    ticketGroup?: string | string[];
    /**
     * Filters for tickets that are spam.
     */
    ticketIsSpam?: boolean;
    /**
     * Filters for tickets that need response.
     */
    ticketNeedsResponse?: boolean;
    /**
     * Filters for tickets that are associated with any of the provided Rev
     * organizations.
     */
    ticketRevOrg?: string | string[];
    /**
     * Filters for tickets with any of the provided severities.
     */
    ticketSeverity?: DevRev.TicketSeverity | DevRev.TicketSeverity[];
    /**
     * Filters for records with any of the provided SLA stages.
     */
    ticketSlaSummaryStage?: DevRev.SlaSummaryStage | DevRev.SlaSummaryStage[];
    /**
     * Filters for tickets with any of the provided source channels.
     */
    ticketSourceChannel?: string | string[];
    /**
     * Filters for tickets with any of the provided subtypes.
     */
    ticketSubtype?: string | string[];
    /**
     * Filters for work of the provided types.
     */
    type?: DevRev.WorkType | DevRev.WorkType[];
}
