/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "string"
 *     }
 */
export interface WorksGetRequest {
    /** The work's ID. */
    id: string;
}
