/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface Article extends DevRev.AtomBase {
    /** Details of the parts relevant to the article. */
    appliesToParts: DevRev.PartSummary[];
    articleType?: DevRev.ArticleType;
    /** Users that authored the article. */
    authoredBy?: DevRev.UserSummary[];
    /** Description of the article. */
    description?: string;
    /** Artifacts containing the extracted content. */
    extractedContent?: DevRev.ArtifactSummary[];
    /** Number of downvotes on the article. */
    numDownvotes?: number;
    /** Number of upvotes on the article. */
    numUpvotes?: number;
    /** The users that own the article. */
    ownedBy: DevRev.UserSummary[];
    parent?: DevRev.DirectorySummary;
    /** Rank of the article. */
    rank?: string;
    resource?: DevRev.Resource;
    scope?: DevRev.EnumValue;
    /** Title of the article. */
    title?: string;
}
