/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BooleanExpressionType = "and" | "not" | "or" | "primitive";

export const BooleanExpressionType = {
    And: "and",
    Not: "not",
    Or: "or",
    Primitive: "primitive",
} as const;
