/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Source of the code change object.
 */
export type CodeChangeSource = "bitbucket" | "github";

export const CodeChangeSource = {
    Bitbucket: "bitbucket",
    Github: "github",
} as const;
