/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface CommentSearchSummary {
    comment?: DevRev.TimelineCommentSummary;
    createdBy?: DevRev.UserSummary;
    /** Timestamp when the comment was created. */
    createdDate?: Date;
    /** Text snippet where the search hit occurred. */
    snippet?: string;
}
