/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ErrorBadRequestMergeWorksErrorErrorDifferentWorkspace {
    /** The workspace of the primary work. */
    primaryWorkspace: string;
    /** The workspace of the secondary work. */
    secondaryWorkspace: string;
}
