/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ErrorBadRequestUnexpectedJsonTypeType = "array" | "bool" | "null" | "number" | "object" | "string";

export const ErrorBadRequestUnexpectedJsonTypeType = {
    Array: "array",
    Bool: "bool",
    Null: "null",
    Number: "number",
    Object: "object",
    String: "string",
} as const;
