/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ErrorBadRequestType =
    | "artifact_already_attached_to_a_parent"
    | "bad_request"
    | "invalid_api_version"
    | "invalid_enum_value"
    | "invalid_field"
    | "invalid_id"
    | "merge_works_error"
    | "missing_dependency"
    | "missing_required_field"
    | "parse_error"
    | "stale_schema_fragments"
    | "unexpected_id_type"
    | "unexpected_json_type"
    | "value_not_permitted";

export const ErrorBadRequestType = {
    ArtifactAlreadyAttachedToAParent: "artifact_already_attached_to_a_parent",
    BadRequest: "bad_request",
    InvalidApiVersion: "invalid_api_version",
    InvalidEnumValue: "invalid_enum_value",
    InvalidField: "invalid_field",
    InvalidId: "invalid_id",
    MergeWorksError: "merge_works_error",
    MissingDependency: "missing_dependency",
    MissingRequiredField: "missing_required_field",
    ParseError: "parse_error",
    StaleSchemaFragments: "stale_schema_fragments",
    UnexpectedIdType: "unexpected_id_type",
    UnexpectedJsonType: "unexpected_json_type",
    ValueNotPermitted: "value_not_permitted",
} as const;
