/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface EventDevUserUpdated {
    devUser: DevRev.DevUser;
    oldDevUser?: DevRev.DevUser;
}
