/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface EventRevUserDeleted {
    /** The ID of the Rev user that was deleted. */
    id: string;
    oldRevUser?: DevRev.RevUser;
}
