/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface EventWorkDeleted {
    /** The ID of the work that was deleted. */
    id: string;
    oldWork?: DevRev.Work;
}
