/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Preferred locale of the user.
 */
export type GeneralPreferencesGroupPreferredLocale = "en_us" | "ja_jp";

export const GeneralPreferencesGroupPreferredLocale = {
    EnUs: "en_us",
    JaJp: "ja_jp",
} as const;
