/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OrgType = "account" | "rev_org";

export const OrgType = {
    Account: "account",
    RevOrg: "rev_org",
} as const;
