/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Logical grouping of snap widgets. Useful for filtering.
 */
export type SnapWidgetNamespace = "comment_suggestion_replies" | "email_preview" | "link_preview" | "plug_nudge";

export const SnapWidgetNamespace = {
    CommentSuggestionReplies: "comment_suggestion_replies",
    EmailPreview: "email_preview",
    LinkPreview: "link_preview",
    PlugNudge: "plug_nudge",
} as const;
