/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Channels of the ticket.
 */
export type TicketChannels = "email" | "plug" | "slack" | "twilio";

export const TicketChannels = {
    Email: "email",
    Plug: "plug",
    Slack: "slack",
    Twilio: "twilio",
} as const;
