/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface TimelineEntriesUpdateRequestTimelineComment {
    artifacts?: DevRev.TimelineEntriesUpdateRequestTimelineCommentArtifacts;
    /** The updated comment's body. */
    body?: string;
    bodyType?: DevRev.TimelineCommentBodyType;
    linkPreviews?: DevRev.TimelineEntriesUpdateRequestTimelineCommentLinkPreviews;
    snapKitBody?: DevRev.TimelineSnapKitBody;
}
