/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface WebhooksUpdateRequestHeaders {
    add?: DevRev.WebhookHeader[];
    remove?: string[];
    set?: DevRev.WebhookHeader[];
}
