/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface WorksUpdateRequestTicket {
    channels?: DevRev.WorksUpdateRequestTicketChannels;
    /** Updates the group that the ticket is associated with. */
    group?: string;
    /** Updates whether the ticket is spam. */
    isSpam?: boolean;
    /** Updates whether the ticket needs a response. */
    needsResponse?: boolean;
    /** Updates the Rev organization that the ticket is associated with. */
    revOrg?: string;
    severity?: DevRev.TicketSeverity;
}
