/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WorksUpdateRequestStagedInfoStagedInfoUpdate {
    /** Updates the unresolved fields of the staged work. */
    unresolvedFields: string[];
}
