/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface DevUsersUpdateRequest {
    /** The updated display name of the Dev user. */
    displayName?: string;
    /** The updated full name of the Dev user. */
    fullName?: string;
    /** The ID for the Dev user to be updated. */
    id: string;
    jobTitle?: DevRev.DevUserJobTitle;
}
