/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "string"
 *     }
 */
export interface CustomSchemaFragmentsGetQuery {
    /**
     * The ID of the custom schema fragment.
     */
    id: string;
}
