/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { TimelineCommentSummary } from "./TimelineCommentSummary";
import { UserSummary } from "./UserSummary";

export const CommentSearchSummary: core.serialization.ObjectSchema<
    serializers.CommentSearchSummary.Raw,
    DevRev.CommentSearchSummary
> = core.serialization.object({
    comment: TimelineCommentSummary.optional(),
    createdBy: core.serialization.property("created_by", UserSummary.optional()),
    createdDate: core.serialization.property("created_date", core.serialization.date().optional()),
    snippet: core.serialization.string().optional(),
});

export declare namespace CommentSearchSummary {
    interface Raw {
        comment?: TimelineCommentSummary.Raw | null;
        created_by?: UserSummary.Raw | null;
        created_date?: string | null;
        snippet?: string | null;
    }
}
