/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { AtomBase } from "./AtomBase";

export const CustomState: core.serialization.ObjectSchema<serializers.CustomState.Raw, DevRev.CustomState> = AtomBase;

export declare namespace CustomState {
    type Raw = AtomBase.Raw;
}
