/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const DateTimePresetType: core.serialization.Schema<
    serializers.DateTimePresetType.Raw,
    DevRev.DateTimePresetType
> = core.serialization.enum_(["last_n_days", "next_n_days"]);

export declare namespace DateTimePresetType {
    type Raw = "last_n_days" | "next_n_days";
}
