/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../core";
import * as serializers from "../index";
import * as DevRev from "../../api/index";
import { AuthConnectionOptionsGoogleApps } from "./AuthConnectionOptionsGoogleApps";
import { AuthConnectionOptionsOidc } from "./AuthConnectionOptionsOidc";
import { AuthConnectionOptionsSaml } from "./AuthConnectionOptionsSaml";
import { AuthConnectionOptionsAzureAd } from "./AuthConnectionOptionsAzureAd";

const _Base = core.serialization.object({
    displayName: core.serialization.property("display_name", core.serialization.string().optional()),
});
export const DevOrgAuthConnectionsCreateRequest: core.serialization.Schema<
    serializers.DevOrgAuthConnectionsCreateRequest.Raw,
    DevRev.DevOrgAuthConnectionsCreateRequest
> = core.serialization
    .union("type", {
        google_apps: AuthConnectionOptionsGoogleApps.extend(_Base),
        oidc: AuthConnectionOptionsOidc.extend(_Base),
        samlp: AuthConnectionOptionsSaml.extend(_Base),
        waad: AuthConnectionOptionsAzureAd.extend(_Base),
    })
    .transform<DevRev.DevOrgAuthConnectionsCreateRequest>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace DevOrgAuthConnectionsCreateRequest {
    type Raw =
        | DevOrgAuthConnectionsCreateRequest.GoogleApps
        | DevOrgAuthConnectionsCreateRequest.Oidc
        | DevOrgAuthConnectionsCreateRequest.Samlp
        | DevOrgAuthConnectionsCreateRequest.Waad;

    interface GoogleApps extends _Base, AuthConnectionOptionsGoogleApps.Raw {
        type: "google_apps";
    }

    interface Oidc extends _Base, AuthConnectionOptionsOidc.Raw {
        type: "oidc";
    }

    interface Samlp extends _Base, AuthConnectionOptionsSaml.Raw {
        type: "samlp";
    }

    interface Waad extends _Base, AuthConnectionOptionsAzureAd.Raw {
        type: "waad";
    }

    interface _Base {
        display_name?: string | null;
    }
}
