/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const ErrorBadRequestStaleSchemaFragments: core.serialization.Schema<
    serializers.ErrorBadRequestStaleSchemaFragments.Raw,
    DevRev.ErrorBadRequestStaleSchemaFragments
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace ErrorBadRequestStaleSchemaFragments {
    type Raw = Record<string, unknown>;
}
