/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const ErrorBadRequestValueNotPermitted: core.serialization.ObjectSchema<
    serializers.ErrorBadRequestValueNotPermitted.Raw,
    DevRev.ErrorBadRequestValueNotPermitted
> = core.serialization.object({
    allowedValues: core.serialization.property(
        "allowed_values",
        core.serialization.list(core.serialization.string()).optional()
    ),
    fieldName: core.serialization.property("field_name", core.serialization.string()),
    reason: core.serialization.string().optional(),
});

export declare namespace ErrorBadRequestValueNotPermitted {
    interface Raw {
        allowed_values?: string[] | null;
        field_name: string;
        reason?: string | null;
    }
}
