/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const ErrorConflictConflict: core.serialization.Schema<
    serializers.ErrorConflictConflict.Raw,
    DevRev.ErrorConflictConflict
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace ErrorConflictConflict {
    type Raw = Record<string, unknown>;
}
