/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { ErrorBadRequestMissingDependencyDependency } from "./ErrorBadRequestMissingDependencyDependency";

export const ErrorBadRequestMissingDependency: core.serialization.ObjectSchema<
    serializers.ErrorBadRequestMissingDependency.Raw,
    DevRev.ErrorBadRequestMissingDependency
> = core.serialization.object({
    dependencies: core.serialization.list(ErrorBadRequestMissingDependencyDependency).optional(),
    dependentFieldName: core.serialization.property("dependent_field_name", core.serialization.string().optional()),
    dependentFieldValue: core.serialization.property("dependent_field_value", core.serialization.string().optional()),
    providedFieldName: core.serialization.property("provided_field_name", core.serialization.string().optional()),
    providedFieldValue: core.serialization.property("provided_field_value", core.serialization.string().optional()),
});

export declare namespace ErrorBadRequestMissingDependency {
    interface Raw {
        dependencies?: ErrorBadRequestMissingDependencyDependency.Raw[] | null;
        dependent_field_name?: string | null;
        dependent_field_value?: string | null;
        provided_field_name?: string | null;
        provided_field_value?: string | null;
    }
}
