/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { ErrorBadRequestMergeWorksErrorError } from "./ErrorBadRequestMergeWorksErrorError";

export const ErrorBadRequestMergeWorksError: core.serialization.ObjectSchema<
    serializers.ErrorBadRequestMergeWorksError.Raw,
    DevRev.ErrorBadRequestMergeWorksError
> = core.serialization.object({
    errors: core.serialization.list(ErrorBadRequestMergeWorksErrorError).optional(),
});

export declare namespace ErrorBadRequestMergeWorksError {
    interface Raw {
        errors?: ErrorBadRequestMergeWorksErrorError.Raw[] | null;
    }
}
