/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const ErrorBadRequestUnexpectedIdType: core.serialization.ObjectSchema<
    serializers.ErrorBadRequestUnexpectedIdType.Raw,
    DevRev.ErrorBadRequestUnexpectedIdType
> = core.serialization.object({
    fieldName: core.serialization.property("field_name", core.serialization.string()),
});

export declare namespace ErrorBadRequestUnexpectedIdType {
    interface Raw {
        field_name: string;
    }
}
