/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { DevUser } from "./DevUser";

export const EventDevUserDeleted: core.serialization.ObjectSchema<
    serializers.EventDevUserDeleted.Raw,
    DevRev.EventDevUserDeleted
> = core.serialization.object({
    id: core.serialization.string(),
    oldDevUser: core.serialization.property("old_dev_user", DevUser.optional()),
});

export declare namespace EventDevUserDeleted {
    interface Raw {
        id: string;
        old_dev_user?: DevUser.Raw | null;
    }
}
