/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { TimelineEntry } from "./TimelineEntry";

export const EventTimelineEntryCreated: core.serialization.ObjectSchema<
    serializers.EventTimelineEntryCreated.Raw,
    DevRev.EventTimelineEntryCreated
> = core.serialization.object({
    entry: TimelineEntry,
});

export declare namespace EventTimelineEntryCreated {
    interface Raw {
        entry: TimelineEntry.Raw;
    }
}
