/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { Group } from "./Group";

export const EventGroupUpdated: core.serialization.ObjectSchema<
    serializers.EventGroupUpdated.Raw,
    DevRev.EventGroupUpdated
> = core.serialization.object({
    group: Group,
});

export declare namespace EventGroupUpdated {
    interface Raw {
        group: Group.Raw;
    }
}
