/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { Account } from "./Account";

export const EventAccountDeleted: core.serialization.ObjectSchema<
    serializers.EventAccountDeleted.Raw,
    DevRev.EventAccountDeleted
> = core.serialization.object({
    id: core.serialization.string(),
    oldAccount: core.serialization.property("old_account", Account.optional()),
});

export declare namespace EventAccountDeleted {
    interface Raw {
        id: string;
        old_account?: Account.Raw | null;
    }
}
