/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { Tag } from "./Tag";

export const EventTagUpdated: core.serialization.ObjectSchema<serializers.EventTagUpdated.Raw, DevRev.EventTagUpdated> =
    core.serialization.object({
        tag: Tag,
    });

export declare namespace EventTagUpdated {
    interface Raw {
        tag: Tag.Raw;
    }
}
