/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { RevUser } from "./RevUser";

export const EventRevUserUpdated: core.serialization.ObjectSchema<
    serializers.EventRevUserUpdated.Raw,
    DevRev.EventRevUserUpdated
> = core.serialization.object({
    oldRevUser: core.serialization.property("old_rev_user", RevUser.optional()),
    revUser: core.serialization.property("rev_user", RevUser),
});

export declare namespace EventRevUserUpdated {
    interface Raw {
        old_rev_user?: RevUser.Raw | null;
        rev_user: RevUser.Raw;
    }
}
