/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { SurveyResponse } from "./SurveyResponse";

export const EventSurveyResponseUpdated: core.serialization.ObjectSchema<
    serializers.EventSurveyResponseUpdated.Raw,
    DevRev.EventSurveyResponseUpdated
> = core.serialization.object({
    surveyResponse: core.serialization.property("survey_response", SurveyResponse),
});

export declare namespace EventSurveyResponseUpdated {
    interface Raw {
        survey_response: SurveyResponse.Raw;
    }
}
