/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const GeneralPreferencesGroupPreferredLocale: core.serialization.Schema<
    serializers.GeneralPreferencesGroupPreferredLocale.Raw,
    DevRev.GeneralPreferencesGroupPreferredLocale
> = core.serialization.enum_(["en_us", "es_ar", "ja_jp", "nl_aw", "nl_sx"]);

export declare namespace GeneralPreferencesGroupPreferredLocale {
    type Raw = "en_us" | "es_ar" | "ja_jp" | "nl_aw" | "nl_sx";
}
