/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { CustomStageSummary } from "./CustomStageSummary";

export const LegacyStage: core.serialization.ObjectSchema<serializers.LegacyStage.Raw, DevRev.LegacyStage> =
    core.serialization.object({
        name: core.serialization.string(),
        stage: CustomStageSummary.optional(),
    });

export declare namespace LegacyStage {
    interface Raw {
        name: string;
        stage?: CustomStageSummary.Raw | null;
    }
}
