/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const SchemaFieldDescriptorFieldType: core.serialization.Schema<
    serializers.SchemaFieldDescriptorFieldType.Raw,
    DevRev.SchemaFieldDescriptorFieldType
> = core.serialization.enum_([
    "array",
    "bool",
    "composite",
    "date",
    "double",
    "enum",
    "id",
    "int",
    "rich_text",
    "struct",
    "text",
    "timestamp",
    "tokens",
    "uenum",
    "unknown",
]);

export declare namespace SchemaFieldDescriptorFieldType {
    type Raw =
        | "array"
        | "bool"
        | "composite"
        | "date"
        | "double"
        | "enum"
        | "id"
        | "int"
        | "rich_text"
        | "struct"
        | "text"
        | "timestamp"
        | "tokens"
        | "uenum"
        | "unknown";
}
