/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const SetSharedWithMembership: core.serialization.Schema<
    serializers.SetSharedWithMembership.Raw,
    DevRev.SetSharedWithMembership
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace SetSharedWithMembership {
    type Raw = Record<string, unknown>;
}
