/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const SharedWithMembershipFilter: core.serialization.Schema<
    serializers.SharedWithMembershipFilter.Raw,
    DevRev.SharedWithMembershipFilter
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace SharedWithMembershipFilter {
    type Raw = Record<string, unknown>;
}
