/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const SnapWidgetNamespace: core.serialization.Schema<
    serializers.SnapWidgetNamespace.Raw,
    DevRev.SnapWidgetNamespace
> = core.serialization.enum_(["comment_suggestion_replies", "email_preview", "link_preview", "plug_nudge"]);

export declare namespace SnapWidgetNamespace {
    type Raw = "comment_suggestion_replies" | "email_preview" | "link_preview" | "plug_nudge";
}
