/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { TimelineComment } from "./TimelineComment";

export const TimelineEntry: core.serialization.Schema<serializers.TimelineEntry.Raw, DevRev.TimelineEntry> =
    core.serialization
        .union("type", {
            timeline_comment: TimelineComment,
        })
        .transform<DevRev.TimelineEntry>({
            transform: (value) => value,
            untransform: (value) => value,
        });

export declare namespace TimelineEntry {
    type Raw = TimelineEntry.TimelineComment;

    interface TimelineComment extends TimelineComment.Raw {
        type: "timeline_comment";
    }
}
