/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { WebhookEventType } from "./WebhookEventType";
import { EventAccountCreated } from "./EventAccountCreated";
import { EventAccountDeleted } from "./EventAccountDeleted";
import { EventAccountUpdated } from "./EventAccountUpdated";
import { EventConversationCreated } from "./EventConversationCreated";
import { EventConversationDeleted } from "./EventConversationDeleted";
import { EventConversationUpdated } from "./EventConversationUpdated";
import { EventDevUserCreated } from "./EventDevUserCreated";
import { EventDevUserDeleted } from "./EventDevUserDeleted";
import { EventDevUserUpdated } from "./EventDevUserUpdated";
import { EventGroupCreated } from "./EventGroupCreated";
import { EventGroupDeleted } from "./EventGroupDeleted";
import { EventGroupUpdated } from "./EventGroupUpdated";
import { EventPartCreated } from "./EventPartCreated";
import { EventPartDeleted } from "./EventPartDeleted";
import { EventPartUpdated } from "./EventPartUpdated";
import { EventRevOrgCreated } from "./EventRevOrgCreated";
import { EventRevOrgDeleted } from "./EventRevOrgDeleted";
import { EventRevOrgUpdated } from "./EventRevOrgUpdated";
import { EventRevUserCreated } from "./EventRevUserCreated";
import { EventRevUserDeleted } from "./EventRevUserDeleted";
import { EventRevUserUpdated } from "./EventRevUserUpdated";
import { EventSlaTrackerCreated } from "./EventSlaTrackerCreated";
import { EventSlaTrackerDeleted } from "./EventSlaTrackerDeleted";
import { EventSlaTrackerUpdated } from "./EventSlaTrackerUpdated";
import { EventSurveyResponseCreated } from "./EventSurveyResponseCreated";
import { EventSurveyResponseDeleted } from "./EventSurveyResponseDeleted";
import { EventSurveyResponseUpdated } from "./EventSurveyResponseUpdated";
import { EventTagCreated } from "./EventTagCreated";
import { EventTagDeleted } from "./EventTagDeleted";
import { EventTagUpdated } from "./EventTagUpdated";
import { EventTimelineEntryCreated } from "./EventTimelineEntryCreated";
import { EventTimelineEntryDeleted } from "./EventTimelineEntryDeleted";
import { EventTimelineEntryUpdated } from "./EventTimelineEntryUpdated";
import { WebhookEventVerify } from "./WebhookEventVerify";
import { EventWebhookCreated } from "./EventWebhookCreated";
import { EventWebhookDeleted } from "./EventWebhookDeleted";
import { EventWebhookUpdated } from "./EventWebhookUpdated";
import { EventWorkCreated } from "./EventWorkCreated";
import { EventWorkDeleted } from "./EventWorkDeleted";
import { EventWorkUpdated } from "./EventWorkUpdated";

export const WebhookEventRequest: core.serialization.ObjectSchema<
    serializers.WebhookEventRequest.Raw,
    DevRev.WebhookEventRequest
> = core.serialization.object({
    type: WebhookEventType.optional(),
    accountCreated: core.serialization.property("account_created", EventAccountCreated.optional()),
    accountDeleted: core.serialization.property("account_deleted", EventAccountDeleted.optional()),
    accountUpdated: core.serialization.property("account_updated", EventAccountUpdated.optional()),
    conversationCreated: core.serialization.property("conversation_created", EventConversationCreated.optional()),
    conversationDeleted: core.serialization.property("conversation_deleted", EventConversationDeleted.optional()),
    conversationUpdated: core.serialization.property("conversation_updated", EventConversationUpdated.optional()),
    devUserCreated: core.serialization.property("dev_user_created", EventDevUserCreated.optional()),
    devUserDeleted: core.serialization.property("dev_user_deleted", EventDevUserDeleted.optional()),
    devUserUpdated: core.serialization.property("dev_user_updated", EventDevUserUpdated.optional()),
    groupCreated: core.serialization.property("group_created", EventGroupCreated.optional()),
    groupDeleted: core.serialization.property("group_deleted", EventGroupDeleted.optional()),
    groupUpdated: core.serialization.property("group_updated", EventGroupUpdated.optional()),
    id: core.serialization.string(),
    partCreated: core.serialization.property("part_created", EventPartCreated.optional()),
    partDeleted: core.serialization.property("part_deleted", EventPartDeleted.optional()),
    partUpdated: core.serialization.property("part_updated", EventPartUpdated.optional()),
    revOrgCreated: core.serialization.property("rev_org_created", EventRevOrgCreated.optional()),
    revOrgDeleted: core.serialization.property("rev_org_deleted", EventRevOrgDeleted.optional()),
    revOrgUpdated: core.serialization.property("rev_org_updated", EventRevOrgUpdated.optional()),
    revUserCreated: core.serialization.property("rev_user_created", EventRevUserCreated.optional()),
    revUserDeleted: core.serialization.property("rev_user_deleted", EventRevUserDeleted.optional()),
    revUserUpdated: core.serialization.property("rev_user_updated", EventRevUserUpdated.optional()),
    slaTrackerCreated: core.serialization.property("sla_tracker_created", EventSlaTrackerCreated.optional()),
    slaTrackerDeleted: core.serialization.property("sla_tracker_deleted", EventSlaTrackerDeleted.optional()),
    slaTrackerUpdated: core.serialization.property("sla_tracker_updated", EventSlaTrackerUpdated.optional()),
    surveyResponseCreated: core.serialization.property(
        "survey_response_created",
        EventSurveyResponseCreated.optional()
    ),
    surveyResponseDeleted: core.serialization.property(
        "survey_response_deleted",
        EventSurveyResponseDeleted.optional()
    ),
    surveyResponseUpdated: core.serialization.property(
        "survey_response_updated",
        EventSurveyResponseUpdated.optional()
    ),
    tagCreated: core.serialization.property("tag_created", EventTagCreated.optional()),
    tagDeleted: core.serialization.property("tag_deleted", EventTagDeleted.optional()),
    tagUpdated: core.serialization.property("tag_updated", EventTagUpdated.optional()),
    timelineEntryCreated: core.serialization.property("timeline_entry_created", EventTimelineEntryCreated.optional()),
    timelineEntryDeleted: core.serialization.property("timeline_entry_deleted", EventTimelineEntryDeleted.optional()),
    timelineEntryUpdated: core.serialization.property("timeline_entry_updated", EventTimelineEntryUpdated.optional()),
    timestamp: core.serialization.date().optional(),
    verify: WebhookEventVerify.optional(),
    webhookCreated: core.serialization.property("webhook_created", EventWebhookCreated.optional()),
    webhookDeleted: core.serialization.property("webhook_deleted", EventWebhookDeleted.optional()),
    webhookId: core.serialization.property("webhook_id", core.serialization.string()),
    webhookUpdated: core.serialization.property("webhook_updated", EventWebhookUpdated.optional()),
    workCreated: core.serialization.property("work_created", EventWorkCreated.optional()),
    workDeleted: core.serialization.property("work_deleted", EventWorkDeleted.optional()),
    workUpdated: core.serialization.property("work_updated", EventWorkUpdated.optional()),
});

export declare namespace WebhookEventRequest {
    interface Raw {
        type?: WebhookEventType.Raw | null;
        account_created?: EventAccountCreated.Raw | null;
        account_deleted?: EventAccountDeleted.Raw | null;
        account_updated?: EventAccountUpdated.Raw | null;
        conversation_created?: EventConversationCreated.Raw | null;
        conversation_deleted?: EventConversationDeleted.Raw | null;
        conversation_updated?: EventConversationUpdated.Raw | null;
        dev_user_created?: EventDevUserCreated.Raw | null;
        dev_user_deleted?: EventDevUserDeleted.Raw | null;
        dev_user_updated?: EventDevUserUpdated.Raw | null;
        group_created?: EventGroupCreated.Raw | null;
        group_deleted?: EventGroupDeleted.Raw | null;
        group_updated?: EventGroupUpdated.Raw | null;
        id: string;
        part_created?: EventPartCreated.Raw | null;
        part_deleted?: EventPartDeleted.Raw | null;
        part_updated?: EventPartUpdated.Raw | null;
        rev_org_created?: EventRevOrgCreated.Raw | null;
        rev_org_deleted?: EventRevOrgDeleted.Raw | null;
        rev_org_updated?: EventRevOrgUpdated.Raw | null;
        rev_user_created?: EventRevUserCreated.Raw | null;
        rev_user_deleted?: EventRevUserDeleted.Raw | null;
        rev_user_updated?: EventRevUserUpdated.Raw | null;
        sla_tracker_created?: EventSlaTrackerCreated.Raw | null;
        sla_tracker_deleted?: EventSlaTrackerDeleted.Raw | null;
        sla_tracker_updated?: EventSlaTrackerUpdated.Raw | null;
        survey_response_created?: EventSurveyResponseCreated.Raw | null;
        survey_response_deleted?: EventSurveyResponseDeleted.Raw | null;
        survey_response_updated?: EventSurveyResponseUpdated.Raw | null;
        tag_created?: EventTagCreated.Raw | null;
        tag_deleted?: EventTagDeleted.Raw | null;
        tag_updated?: EventTagUpdated.Raw | null;
        timeline_entry_created?: EventTimelineEntryCreated.Raw | null;
        timeline_entry_deleted?: EventTimelineEntryDeleted.Raw | null;
        timeline_entry_updated?: EventTimelineEntryUpdated.Raw | null;
        timestamp?: string | null;
        verify?: WebhookEventVerify.Raw | null;
        webhook_created?: EventWebhookCreated.Raw | null;
        webhook_deleted?: EventWebhookDeleted.Raw | null;
        webhook_id: string;
        webhook_updated?: EventWebhookUpdated.Raw | null;
        work_created?: EventWorkCreated.Raw | null;
        work_deleted?: EventWorkDeleted.Raw | null;
        work_updated?: EventWorkUpdated.Raw | null;
    }
}
