/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const WebhookEventType: core.serialization.Schema<serializers.WebhookEventType.Raw, DevRev.WebhookEventType> =
    core.serialization.enum_([
        "account_created",
        "account_deleted",
        "account_updated",
        "conversation_created",
        "conversation_deleted",
        "conversation_updated",
        "dev_user_created",
        "dev_user_deleted",
        "dev_user_updated",
        "group_created",
        "group_deleted",
        "group_updated",
        "part_created",
        "part_deleted",
        "part_updated",
        "rev_org_created",
        "rev_org_deleted",
        "rev_org_updated",
        "rev_user_created",
        "rev_user_deleted",
        "rev_user_updated",
        "sla_tracker_created",
        "sla_tracker_deleted",
        "sla_tracker_updated",
        "tag_created",
        "tag_deleted",
        "tag_updated",
        "timeline_entry_created",
        "timeline_entry_deleted",
        "timeline_entry_updated",
        "verify",
        "webhook_created",
        "webhook_deleted",
        "webhook_updated",
        "work_created",
        "work_deleted",
        "work_updated",
    ]);

export declare namespace WebhookEventType {
    type Raw =
        | "account_created"
        | "account_deleted"
        | "account_updated"
        | "conversation_created"
        | "conversation_deleted"
        | "conversation_updated"
        | "dev_user_created"
        | "dev_user_deleted"
        | "dev_user_updated"
        | "group_created"
        | "group_deleted"
        | "group_updated"
        | "part_created"
        | "part_deleted"
        | "part_updated"
        | "rev_org_created"
        | "rev_org_deleted"
        | "rev_org_updated"
        | "rev_user_created"
        | "rev_user_deleted"
        | "rev_user_updated"
        | "sla_tracker_created"
        | "sla_tracker_deleted"
        | "sla_tracker_updated"
        | "tag_created"
        | "tag_deleted"
        | "tag_updated"
        | "timeline_entry_created"
        | "timeline_entry_deleted"
        | "timeline_entry_updated"
        | "verify"
        | "webhook_created"
        | "webhook_deleted"
        | "webhook_updated"
        | "work_created"
        | "work_deleted"
        | "work_updated";
}
