/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface IncidentsUpdateRequest {
    appliesToParts?: DevRev.UpdateIncidentAppliesToParts;
    artifacts?: DevRev.UpdateIncidentArtifacts;
    /** Body of the incident. */
    body?: string;
    /** Application-defined custom fields. */
    customFields?: Record<string, unknown>;
    customSchemaSpec?: DevRev.CustomSchemaSpec;
    /** The ID of the incident to be updated. */
    id: string;
    /** Time when the incident was identified/reported. */
    identifiedAt?: Date;
    impactedCustomers?: DevRev.UpdateIncidentImpactedCustomers;
    ownedBy?: DevRev.UpdateIncidentOwnedBy;
    /** Timestamp when the incident was resolved. */
    resolvedAt?: Date;
    /** Severity of the incident. */
    severity?: number;
    stage?: DevRev.UpdateStage;
    stakeholders?: DevRev.UpdateIncidentStakeholders;
    tags?: DevRev.UpdateIncidentTags;
    /** Timestamp when the incident is expected to be resolved. */
    targetCloseDate?: Date;
    /** Title of the incident. */
    title?: string;
}
