/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";
import { UpdateIncidentAppliesToParts } from "../../../../types/UpdateIncidentAppliesToParts";
import { UpdateIncidentArtifacts } from "../../../../types/UpdateIncidentArtifacts";
import { CustomSchemaSpec } from "../../../../types/CustomSchemaSpec";
import { UpdateIncidentImpactedCustomers } from "../../../../types/UpdateIncidentImpactedCustomers";
import { UpdateIncidentOwnedBy } from "../../../../types/UpdateIncidentOwnedBy";
import { UpdateStage } from "../../../../types/UpdateStage";
import { UpdateIncidentStakeholders } from "../../../../types/UpdateIncidentStakeholders";
import { UpdateIncidentTags } from "../../../../types/UpdateIncidentTags";

export const IncidentsUpdateRequest: core.serialization.Schema<
    serializers.IncidentsUpdateRequest.Raw,
    DevRev.IncidentsUpdateRequest
> = core.serialization.object({
    appliesToParts: core.serialization.property("applies_to_parts", UpdateIncidentAppliesToParts.optional()),
    artifacts: UpdateIncidentArtifacts.optional(),
    body: core.serialization.string().optional(),
    customFields: core.serialization.property(
        "custom_fields",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional()
    ),
    customSchemaSpec: core.serialization.property("custom_schema_spec", CustomSchemaSpec.optional()),
    id: core.serialization.string(),
    identifiedAt: core.serialization.property("identified_at", core.serialization.date().optional()),
    impactedCustomers: core.serialization.property("impacted_customers", UpdateIncidentImpactedCustomers.optional()),
    ownedBy: core.serialization.property("owned_by", UpdateIncidentOwnedBy.optional()),
    resolvedAt: core.serialization.property("resolved_at", core.serialization.date().optional()),
    severity: core.serialization.number().optional(),
    stage: UpdateStage.optional(),
    stakeholders: UpdateIncidentStakeholders.optional(),
    tags: UpdateIncidentTags.optional(),
    targetCloseDate: core.serialization.property("target_close_date", core.serialization.date().optional()),
    title: core.serialization.string().optional(),
});

export declare namespace IncidentsUpdateRequest {
    interface Raw {
        applies_to_parts?: UpdateIncidentAppliesToParts.Raw | null;
        artifacts?: UpdateIncidentArtifacts.Raw | null;
        body?: string | null;
        custom_fields?: Record<string, unknown> | null;
        custom_schema_spec?: CustomSchemaSpec.Raw | null;
        id: string;
        identified_at?: string | null;
        impacted_customers?: UpdateIncidentImpactedCustomers.Raw | null;
        owned_by?: UpdateIncidentOwnedBy.Raw | null;
        resolved_at?: string | null;
        severity?: number | null;
        stage?: UpdateStage.Raw | null;
        stakeholders?: UpdateIncidentStakeholders.Raw | null;
        tags?: UpdateIncidentTags.Raw | null;
        target_close_date?: string | null;
        title?: string | null;
    }
}
